spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
  config:
    import: configserver:http://localhost:8889

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    com.matdev: DEBUG
debug: true

