spring:
  application:
    name: user-service
  cloud:
    config:
      fail-fast: true
  config:
    import: configserver:http://localhost:8889


  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
