spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: your-username
    password: your-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect