spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MatDev/MS-Gestion-Pedidos.git
          search-paths:
            - config-repo/user-service
            - config-repo/gateway
          default-label: main
  application:
    name: config-server
    

server:
  port: 8889


