name: MS-PIPELINE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar dependencias Maven
        run: mvn clean install -DskipTests

      - name: Test unitario, Reportes y Cobertura
        run: mvn verify

      - name: Subir reporte Jacoco
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: user-service/target/site/jacoco/index.html

      - name: Setup Java JDK para Sonar Cloud
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Scan
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectKey=MatDev_MS-Gestion-Pedidos \
          -Dsonar.projectName=MS-Gestion-Pedidos

      - name: SonarCloud Quality Gate
        id: sonarcloud-check
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: user-service/target/sonar/report-task.txt

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Construir y etiquetar imagen de User Service
        run: |
          docker build -t user-service -f user-service/Dockerfile ./user-service
          docker tag user-service:latest ${{ secrets.USERNAME }}/user-service:latest
          docker push ${{ secrets.USERNAME }}/user-service:latest


